package view;

import controler.ClienteController;
import controler.PaisController;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Pais;

public class Home extends javax.swing.JFrame {

    private PaisController pc = new PaisController();
    private ClienteController cc = new ClienteController();

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelErroPais = new javax.swing.JLabel();
        labelErroCliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jbCadastrarCliente = new javax.swing.JMenuItem();
        jbExcluirCliente = new javax.swing.JMenuItem();
        jbAlterarCliente = new javax.swing.JMenuItem();
        jbVisualizarUmCliente = new javax.swing.JMenuItem();
        jbVisualizarTodosClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Países");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Clientes");

        jbCadastrarCliente.setText("Cadastrar");
        jbCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jbCadastrarCliente);

        jbExcluirCliente.setText("Excluir");
        jbExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jbExcluirCliente);

        jbAlterarCliente.setText("Alterar");
        jbAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jbAlterarCliente);

        jbVisualizarUmCliente.setText("Visualizar um Cliente");
        jbVisualizarUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarUmClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jbVisualizarUmCliente);

        jbVisualizarTodosClientes.setText("Visualizar todos Clientes");
        jbVisualizarTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarTodosClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jbVisualizarTodosClientes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelErroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelErroPais, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(133, 133, 133)
                .addComponent(labelErroPais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(labelErroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPais tp = new TelaPais();
        tp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarClienteActionPerformed
        TelaCadastrarCliente tcc = new TelaCadastrarCliente();
        tcc.setVisible(true);
    }//GEN-LAST:event_jbCadastrarClienteActionPerformed

    private void jbExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirClienteActionPerformed
        TelaExcluirCliente tex = new TelaExcluirCliente();
        
        tex.setVisible(true);
    }//GEN-LAST:event_jbExcluirClienteActionPerformed

    private void jbVisualizarUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarUmClienteActionPerformed
        TelaVisualizarCliente vc = new TelaVisualizarCliente();
        vc.setVisible(true);
    }//GEN-LAST:event_jbVisualizarUmClienteActionPerformed

    private void jbVisualizarTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarTodosClientesActionPerformed
        TelaVisualizarTodosClientes vtc = new TelaVisualizarTodosClientes();
        vtc.setVisible(true);
    }//GEN-LAST:event_jbVisualizarTodosClientesActionPerformed

    private void jbAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarClienteActionPerformed
        TelaAlterarCliente ac = new TelaAlterarCliente();
        ac.setVisible(true);
    }//GEN-LAST:event_jbAlterarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jbAlterarCliente;
    private javax.swing.JMenuItem jbCadastrarCliente;
    private javax.swing.JMenuItem jbExcluirCliente;
    private javax.swing.JMenuItem jbVisualizarTodosClientes;
    private javax.swing.JMenuItem jbVisualizarUmCliente;
    private javax.swing.JLabel labelErroCliente;
    private javax.swing.JLabel labelErroPais;
    // End of variables declaration//GEN-END:variables
}
