/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.PaisController;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Pais;

/**
 *
 * @author gabri
 */
public class TelaPais extends javax.swing.JFrame {

    /**
     * Creates new form Pais
     */
    public TelaPais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNomePais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblSigla = new javax.swing.JTextField();
        jbCadastrarPais = new javax.swing.JButton();
        jbExcluirPais = new javax.swing.JButton();
        jbAtualizarPais = new javax.swing.JButton();
        jbVisualizarPais = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIdAtualizarPais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNovoNome = new javax.swing.JTextField();
        lblNovaSigla = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblIdPais = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblIdVisualizar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbVisualizarTodos = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Sigla:");

        lblSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSiglaActionPerformed(evt);
            }
        });

        jbCadastrarPais.setText("Cadastrar");
        jbCadastrarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarPaisActionPerformed(evt);
            }
        });

        jbExcluirPais.setText("Excluir");
        jbExcluirPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirPaisActionPerformed(evt);
            }
        });

        jbAtualizarPais.setText("Atualizar");
        jbAtualizarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarPaisActionPerformed(evt);
            }
        });

        jbVisualizarPais.setText("Visualizar");
        jbVisualizarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarPaisActionPerformed(evt);
            }
        });

        jLabel3.setText("Para cadastrar um país informe os dados abaixo e clique em Cadastrar");

        jLabel4.setText("Para alterar as informações de um pais informe os dados abaixo e clique em Atualizar");

        jLabel5.setText("Para excluir um país informe seu ID e clique em Excluir");

        jLabel6.setText("Para visualizar as informações de um pais específico, informe seu ID e  clique em Visualizar");

        jLabel7.setText("Novo Nome");

        jLabel8.setText("Nova Sigla");

        jLabel9.setText("ID do país a ser alterado");

        lblNovaSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNovaSiglaActionPerformed(evt);
            }
        });

        jLabel10.setText("ID:");

        jLabel11.setText("ID:");

        lblIdVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIdVisualizarActionPerformed(evt);
            }
        });

        jLabel13.setText("Para visualizar todos os países, clique em Visualizar Todos");

        jbVisualizarTodos.setText("Visualizar Todos");
        jbVisualizarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbExcluirPais)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNovaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbAtualizarPais))))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(jbCadastrarPais))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdAtualizarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jbVisualizarPais))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbVisualizarTodos)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrarPais))
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblIdAtualizarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNovaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizarPais))
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluirPais)
                    .addComponent(jLabel10)
                    .addComponent(lblIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblIdVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVisualizarPais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbVisualizarTodos)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSiglaActionPerformed

    private void jbCadastrarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarPaisActionPerformed
        Pais p = new Pais();
        try {
            p.setNome(lblNomePais.getText());
            p.setSigla(lblSigla.getText());
        } catch (Exception ex) {
            Logger.getLogger(TelaPais.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PaisController pc = new PaisController();
        pc.cadastrar(p);

    }//GEN-LAST:event_jbCadastrarPaisActionPerformed

    private void jbExcluirPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirPaisActionPerformed
        PaisController pc = new PaisController();
        
        pc.deletar(Integer.parseInt(lblIdPais.getText()));
    }//GEN-LAST:event_jbExcluirPaisActionPerformed

    private void jbAtualizarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarPaisActionPerformed
        Pais p = new Pais(lblNovoNome.getText(), lblNovaSigla.getText());
        
        PaisController pc = new PaisController();
        
        pc.alterar(p, Integer.parseInt(lblIdAtualizarPais.getText()));
    }//GEN-LAST:event_jbAtualizarPaisActionPerformed

    private void lblNovaSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNovaSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNovaSiglaActionPerformed

    private void lblIdVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIdVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdVisualizarActionPerformed

    private void jbVisualizarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarPaisActionPerformed
        Pais p = new Pais();
        PaisController pc = new PaisController();
        
        p = pc.ler(Integer.parseInt(lblIdVisualizar.getText()));
        
        String msg = p.toString();
        System.out.println(msg);

        
    }//GEN-LAST:event_jbVisualizarPaisActionPerformed

    private void jbVisualizarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarTodosActionPerformed
        PaisController pc = new PaisController();
        ArrayList<Pais> paises = new ArrayList();
        
        paises = pc.lerTodos();
        
        String msg = paises.toString();
        
        System.out.println(msg);
    }//GEN-LAST:event_jbVisualizarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAtualizarPais;
    private javax.swing.JButton jbCadastrarPais;
    private javax.swing.JButton jbExcluirPais;
    private javax.swing.JButton jbVisualizarPais;
    private javax.swing.JButton jbVisualizarTodos;
    private javax.swing.JTextField lblIdAtualizarPais;
    private javax.swing.JTextField lblIdPais;
    private javax.swing.JTextField lblIdVisualizar;
    private javax.swing.JTextField lblNomePais;
    private javax.swing.JTextField lblNovaSigla;
    private javax.swing.JTextField lblNovoNome;
    private javax.swing.JTextField lblSigla;
    // End of variables declaration//GEN-END:variables
}
